version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
phases:
  install:
    runtime-versions:
       java: openjdk8
       docker: 18
    commands:
       - echo installing maven and all other dependencies...
       - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
       - apt-get update -y
       - apt-get install -y maven
  build:
    commands:
    - echo building the CleantipsAPI
    - mvn package dockerfile:build
artifacts:
  files:
  - target/*.jar
  - scripts/*.sh
  discard-paths: yes
cache:
  paths:
  - '/root/.m2/**/*'