version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
phases:
  install:
    runtime-versions:
       java: openjdk8
       docker: 18
    commands:
       - echo installing maven and all other dependences..
       - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --output text --query 'Account')
       - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
       - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.us-west-2.amazonaws.com/cleantips/cleantipsapi
       - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
       - IMAGE_TAG=${COMMIT_HASH:=latest}
  pre_build:
    commands:
      - mvn install dockerfile:build 
  build:
    commands:
    - echo building CleantipsAPI
    - echo Writing image definitions file...
    - printf '[{"name":"cleantipsapi","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:imagedefinitions.json
  - target/*.jar
  discard-paths: yes
cache:
  paths:
  - '/root/.m2/**/*'