version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
phases:
  install:
    runtime-versions:
       java: openjdk8
       docker: 18
    commands:
       - echo installing maven and all other dependences..
       - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --output text --query 'Account')
       - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)  
  pre_build:
    commands:

      - mvn install dockerfile:build 
  build:
    commands:
    - echo building CleantipsAPI
    - docker run -p 8080:8080 -t 1.0.0
artifacts:
  files:
  - target/*.jar
  discard-paths: yes
cache:
  paths:
  - '/root/.m2/**/*'