version: 0.2
env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
phases:
  install:
    runtime-versions:
       java: openjdk8
       docker: 18
    commands:
       - echo installing maven and all other dependences..
       - export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --output text --query 'Account')
       - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
       - apt-get update -y
       - apt-get install -y maven    
  pre_build:
    commands:
      - docker build -t cleantips .
      - docker tag cleantips $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
    - echo building CleantipsAPI
    - mvn package dockerfile:build
    - mvn deploy
artifacts:
  files:
  - target/*.jar
  discard-paths: yes
cache:
  paths:
  - '/root/.m2/**/*'